default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "postgres") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", "5432") %>

development:
  <<: *default
  database: touhou_karaoke_admin_development

test:
  <<: *default
  database: touhou_karaoke_admin_test

production:
  <<: *default
  database: touhou_karaoke_admin_production
  username: touhou_karaoke_admin
  password: <%= ENV['TOUHOU_KARAOKE_ADMIN_DATABASE_PASSWORD'] %>
